env:
  browser: true
  es6: true
  node: true
extends:
  - "eslint:recommended"
  - "google"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:prettier/recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"
  - "plugin:import/typescript"
parser: "@typescript-eslint/parser"
parserOptions:
  project: tsconfig.json
  sourceType: module
plugins:
  - "@typescript-eslint"
  - import
  - deprecation
settings: { "import/parsers": { "@typescript-eslint/parser": [".ts", ".tsx"] }, "import/resolver": { typescript: {} } }
